import type { Column, Dialect, ErdDocument, Relation, Table } from '../erd/model'
import { DIALECT_LABELS, nativeType } from '../erd/dialects'
import { relationKind } from '../erd/relation'
import { defaultDdlExportOptions, type DdlExportOptions, type ReferentialAction } from './options'

function quoteIdent(name: string, dialect: Dialect): string {
  if (dialect === 'mariadb') {
    return `\`${name.replace(/`/g, '``')}\``
  }
  return `"${name.replace(/"/g, '""')}"`
}

function qualify(name: string, options: DdlExportOptions): string {
  const ident = quoteIdent(name, options.dialect)
  const schema = options.schema.trim()
  if (!schema) return ident
  return `${quoteIdent(schema, options.dialect)}.${ident}`
}

function escapeComment(value: string): string {
  return value.replace(/'/g, "''")
}

function identityClause(column: Column, dialect: Dialect): string {
  if (!column.autoIncrement) return ''
  if (dialect === 'mariadb') return ' AUTO_INCREMENT'
  if (dialect === 'postgresql') return ' GENERATED BY DEFAULT AS IDENTITY'
  return ' GENERATED BY DEFAULT AS IDENTITY'
}

function varcharType(column: Column, options: DdlExportOptions): string {
  const raw = nativeType(column, options.dialect)
  if (options.dialect !== 'oracle' || column.logicalType !== 'varchar') return raw
  const length = column.length ?? 255
  return `VARCHAR2(${length} ${options.varcharSemantics})`
}

function columnType(column: Column, options: DdlExportOptions): string {
  if (column.logicalType === 'varchar') return varcharType(column, options)
  return nativeType(column, options.dialect)
}

function columnDefinition(column: Column, options: DdlExportOptions): string {
  const dialect = options.dialect
  const parts = [quoteIdent(column.name, dialect), columnType(column, options)]

  if (!column.nullable) parts.push('NOT NULL')
  if (column.unique && !column.primaryKey) parts.push('UNIQUE')
  parts.push(identityClause(column, dialect).trim())

  if (column.comment && dialect === 'mariadb' && options.includeComments) {
    parts.push(`COMMENT '${escapeComment(column.comment)}'`)
  }

  return `  ${parts.filter(Boolean).join(' ')}`
}

function tableCommentSql(table: Table, options: DdlExportOptions): string[] {
  if (!options.includeComments || !table.comment) return []
  const q = qualify(table.name, options)
  if (options.dialect === 'mariadb') {
    return [`ALTER TABLE ${q} COMMENT = '${escapeComment(table.comment)}';`]
  }
  return [`COMMENT ON TABLE ${q} IS '${escapeComment(table.comment)}';`]
}

function columnCommentSql(table: Table, options: DdlExportOptions): string[] {
  if (!options.includeComments || options.dialect === 'mariadb') return []
  const lines: string[] = []
  for (const column of table.columns) {
    if (!column.comment) continue
    lines.push(
      `COMMENT ON COLUMN ${qualify(table.name, options)}.${quoteIdent(column.name, options.dialect)} IS '${escapeComment(column.comment)}';`
    )
  }
  return lines
}

function tableSuffix(options: DdlExportOptions): string {
  if (options.dialect !== 'mariadb') return ';'
  return `) ENGINE=${options.engine} DEFAULT CHARSET=${options.charset} COLLATE=${options.collation};`
}

function createTableSql(table: Table, options: DdlExportOptions): string {
  const dialect = options.dialect
  const lines = table.columns.map((column) => columnDefinition(column, options))
  const pk = table.columns.filter((c) => c.primaryKey).map((c) => quoteIdent(c.name, dialect))
  if (pk.length > 0) {
    lines.push(`  PRIMARY KEY (${pk.join(', ')})`)
  }
  const exists = options.ifNotExists && dialect !== 'oracle' ? 'IF NOT EXISTS ' : ''
  const open = `CREATE TABLE ${exists}${qualify(table.name, options)} (\n${lines.join(',\n')}\n`
  if (dialect === 'mariadb') return `${open}${tableSuffix(options)}`
  return `${open});`
}

function dropTableSql(table: Table, options: DdlExportOptions): string {
  const name = qualify(table.name, options)
  if (options.dialect === 'oracle') {
    return `DROP TABLE ${name} CASCADE CONSTRAINTS;`
  }
  if (options.dialect === 'postgresql') {
    return `DROP TABLE IF EXISTS ${name} CASCADE;`
  }
  return `DROP TABLE IF EXISTS ${name};`
}

function fkName(relation: Relation, from: Table): string {
  const base = relation.name?.trim() || `fk_${from.name}_${relation.id.slice(0, 8)}`
  return base.replace(/[^\w]/g, '_').slice(0, 30)
}

function actionClause(label: 'DELETE' | 'UPDATE', action: ReferentialAction, dialect: Dialect): string {
  if (action === 'NO ACTION') return ''
  if (dialect === 'oracle' && label === 'UPDATE') return ''
  return `\n  ON ${label} ${action}`
}

function alterFkSql(relation: Relation, tables: Table[], options: DdlExportOptions): string | null {
  if (relationKind(relation) === 'many-to-many') {
    return junctionSql(relation, tables, options)
  }
  const from = tables.find((t) => t.id === relation.fromTableId)
  const to = tables.find((t) => t.id === relation.toTableId)
  if (!from || !to) return null
  const fromCol = from.columns.find((c) => c.id === relation.fromColumnId)
  const toCol = to.columns.find((c) => c.id === relation.toColumnId)
  if (!fromCol || !toCol) return null

  const kind = relationKind(relation)
  const fkTable = kind === 'one-to-many' ? to : from
  const fkCol = kind === 'one-to-many' ? toCol : fromCol
  const pkTable = kind === 'one-to-many' ? from : to
  const pkCol = kind === 'one-to-many' ? fromCol : toCol
  const dialect = options.dialect

  return [
    `ALTER TABLE ${qualify(fkTable.name, options)}`,
    `  ADD CONSTRAINT ${quoteIdent(fkName(relation, fkTable), dialect)}`,
    `  FOREIGN KEY (${quoteIdent(fkCol.name, dialect)})`,
    `  REFERENCES ${qualify(pkTable.name, options)} (${quoteIdent(pkCol.name, dialect)})${actionClause('DELETE', options.onDelete, dialect)}${actionClause('UPDATE', options.onUpdate, dialect)};`
  ].join('\n')
}

function junctionSql(relation: Relation, tables: Table[], options: DdlExportOptions): string | null {
  const from = tables.find((t) => t.id === relation.fromTableId)
  const to = tables.find((t) => t.id === relation.toTableId)
  if (!from || !to) return null
  const fromCol = from.columns.find((c) => c.id === relation.fromColumnId)
  const toCol = to.columns.find((c) => c.id === relation.toColumnId)
  if (!fromCol || !toCol) return null
  const dialect = options.dialect
  const name = relation.name?.trim() || `${from.name}_${to.name}`
  const left = `${from.name}_id`
  const right = `${to.name}_id`
  const exists = options.ifNotExists && dialect !== 'oracle' ? 'IF NOT EXISTS ' : ''
  const drop =
    options.dropExisting && dialect === 'oracle'
      ? `DROP TABLE ${qualify(name, options)} CASCADE CONSTRAINTS;`
      : options.dropExisting
        ? dialect === 'postgresql'
          ? `DROP TABLE IF EXISTS ${qualify(name, options)} CASCADE;`
          : `DROP TABLE IF EXISTS ${qualify(name, options)};`
        : ''
  const createHead = `CREATE TABLE ${exists}${qualify(name, options)} (`
  const body = [
    `  ${quoteIdent(left, dialect)} ${columnType(fromCol, options)} NOT NULL,`,
    `  ${quoteIdent(right, dialect)} ${columnType(toCol, options)} NOT NULL,`,
    `  PRIMARY KEY (${quoteIdent(left, dialect)}, ${quoteIdent(right, dialect)})`
  ].join('\n')
  const create =
    dialect === 'mariadb' ? `${createHead}\n${body}\n${tableSuffix(options)}` : `${createHead}\n${body}\n);`
  const fk = [
    `ALTER TABLE ${qualify(name, options)}`,
    `  ADD CONSTRAINT ${quoteIdent(`fk_${name}_${from.name}`.slice(0, 30), dialect)}`,
    `  FOREIGN KEY (${quoteIdent(left, dialect)}) REFERENCES ${qualify(from.name, options)} (${quoteIdent(fromCol.name, dialect)})`,
    `${actionClause('DELETE', options.onDelete, dialect)}${actionClause('UPDATE', options.onUpdate, dialect)};`,
    `ALTER TABLE ${qualify(name, options)}`,
    `  ADD CONSTRAINT ${quoteIdent(`fk_${name}_${to.name}`.slice(0, 30), dialect)}`,
    `  FOREIGN KEY (${quoteIdent(right, dialect)}) REFERENCES ${qualify(to.name, options)} (${quoteIdent(toCol.name, dialect)})`,
    `${actionClause('DELETE', options.onDelete, dialect)}${actionClause('UPDATE', options.onUpdate, dialect)};`
  ].join('\n')
  return [`-- N:N ${from.name} / ${to.name}`, drop, create, fk].filter(Boolean).join('\n')
}

export function generateDdl(
  document: ErdDocument,
  input: Partial<DdlExportOptions> = {}
): string {
  const options: DdlExportOptions = {
    ...defaultDdlExportOptions(input.dialect ?? document.dialect),
    ...input,
    dialect: input.dialect ?? document.dialect
  }
  const dialect = options.dialect
  const header = [
    `-- Nerd generated DDL`,
    `-- dialect: ${DIALECT_LABELS[dialect]}`,
    `-- document: ${document.name}`
  ]
  if (options.schema.trim()) header.push(`-- schema: ${options.schema.trim()}`)
  header.push('')

  const drops = options.dropExisting
    ? [...document.tables].reverse().map((table) => dropTableSql(table, options))
    : []
  const tables = document.tables.map((table) => createTableSql(table, options))
  const comments = document.tables.flatMap((table) => [
    ...tableCommentSql(table, options),
    ...columnCommentSql(table, options)
  ])
  const fks = options.includeForeignKeys
    ? document.relations
        .map((relation) => alterFkSql(relation, document.tables, options))
        .filter((sql): sql is string => Boolean(sql))
    : []

  return (
    [...header, ...drops, ...tables, '', ...comments, '', ...fks, '']
      .filter((line, i, arr) => {
        if (line !== '') return true
        return arr[i - 1] !== ''
      })
      .join('\n')
      .trim() + '\n'
  )
}
